#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<BusyOrNot> BusyOrNots
	{
		get
		{
			return this.GetTable<BusyOrNot>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BusyOrNot")]
public partial class BusyOrNot
{
	
	private System.Nullable<int> _BusyDayID;
	
	private System.Nullable<System.DateTime> _BusyDay;
	
	private string _Description;
	
	public BusyOrNot()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusyDayID", DbType="Int")]
	public System.Nullable<int> BusyDayID
	{
		get
		{
			return this._BusyDayID;
		}
		set
		{
			if ((this._BusyDayID != value))
			{
				this._BusyDayID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusyDay", DbType="DateTime")]
	public System.Nullable<System.DateTime> BusyDay
	{
		get
		{
			return this._BusyDay;
		}
		set
		{
			if ((this._BusyDay != value))
			{
				this._BusyDay = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}
#pragma warning restore 1591
